spring.application.name=blood_donor_finder
# MySQL Database connection

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialect for MySQL 8 or later (change if you use older version)
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Server port (optional, default is 8080)
server.port=${PORT:8080}

logging.level.org.springframework.security=DEBUG

